"""Packed fixed4x6 glyph data, ASCII 32..126.

Generated by scripts/build_fonts.py from fonts/4x6.bdf -- do not edit by hand.
DATA is base64 of np.packbits() over a (COUNT, CELL_H, CELL_W) bool array.
"""

NAME = "fixed4x6"
SOURCE = "fonts/4x6.bdf"
CELL_W = 4
CELL_H = 6
FIRST = 32
COUNT = 95
DATA = (
    "AAAAREBAqgAAr6+gTsLkgkggSkpQRAAAJERChERIpOSgRORAAABIAOAAAABAIkiASupATETg"
    "SiTg4kLAquIg6MLAaMpA4kiAakrASmLABABABABIJIQgDg4AhCSAwkBAaqhgSuqgysrASopA"
    "yqrA6Mjg6MiAaKpgquqg5ETgIipAqsqgiIjgruqgKuqASqpAysiASqpCysqgaELA5ERAqqrg"
    "qq5Aqu6gqkqgqkRA4kjgZERgiEIgxETASgAAAAAOQgAABqpgjKrABohgJqpgBKxgJORABqYs"
    "jKqgQMTgICIsisqgxETgCuqgDKqgBKpADKyIBqpiCsiABsLATkQgCqpgCqpACq6gCkSgCqYs"
    "DiTgJMRCRERAhGRIWgAA"
)
