"""Packed tomthumb glyph data, ASCII 32..126.

Generated by scripts/build_fonts.py from fonts/tom-thumb.bdf -- do not edit by hand.
DATA is base64 of np.packbits() over a (COUNT, CELL_H, CELL_W) bool array.
"""

NAME = "tomthumb"
SOURCE = "fonts/tom-thumb.bdf"
CELL_W = 4
CELL_H = 6
FIRST = 32
COUNT = 95
DATA = (
    "AAAAREBAqgAArq6gbGxAgkggzOpgRAAAJEQghESApKAABOQAAASAAOAAAABAIkiAaqrATERA"
    "wkjgwkLAquIg6MLAaOrg4kiA6urg6uLABAQABASAJIQgDg4AhCSA4kBASuhgSuqgysrAaIhg"
    "yqrA6Ojg6OiAaOpgquqg5ETgIipAqsqgiIjgruqgru6gSqpAysiASq5gyuygaELA5ERAqqpg"
    "qqRAqu6gqkqgqkRA4kjg6IjgCEIA4iLgSgAAAADghAAADGrgjKrABohgJqpgBqxgJORABq4k"
    "jKqgQERAICKkisygxETgDu6gDKqgBKpADKrIBqpiBoiABsbATkRgCqpgCq5ACu7gCkSgCqYk"
    "DmzgZIRgRARAxCTAbAAA"
)
